// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf9SG-ul8NXwj7u_-zPY1RC7d_EwZHnk4',
    appId: '1:142440317968:web:309bf7585e60641d1c7695',
    messagingSenderId: '142440317968',
    projectId: 'ceesoiree',
    authDomain: 'ceesoiree.firebaseapp.com',
    storageBucket: 'ceesoiree.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0JjBlDd-pVnMPtFMW2hpMgMwG_YnH6M',
    appId: '1:142440317968:android:de96eadcbe08b3f91c7695',
    messagingSenderId: '142440317968',
    projectId: 'ceesoiree',
    storageBucket: 'ceesoiree.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOX8-ZEtsS1pIoWhd7_ndoJhz8De_6GLk',
    appId: '1:142440317968:ios:dc77f4469b69b6861c7695',
    messagingSenderId: '142440317968',
    projectId: 'ceesoiree',
    storageBucket: 'ceesoiree.appspot.com',
    iosClientId: '142440317968-cr1oqeg2bpatfgnevbj2d5m08ofhol41.apps.googleusercontent.com',
    iosBundleId: 'dev.soiree',
  );
}
